[mypy]
python_version = 3.12
files = ratelimiter

check_untyped_defs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True

warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True

no_implicit_optional = True
strict_optional = True

ignore_missing_imports = True
disable_error_code = union-attr,assignment,arg-type,call-arg,return-value,unused-ignore,attr-defined,unused-coroutine,override
