# pytest.ini
[pytest]
; asyncio_mode = auto
# Directories or files to search for tests
testpaths = tests

# Patterns for test file discovery
python_files = test_*.py *_test.py

# Patterns for test class discovery
python_classes = Test* *Tests

# Patterns for test function discovery
python_functions = test_* check_*

# Logging configuration
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

# 排除所有 models.py
norecursedirs = */models.py
